spring:
  datasource:
    url: jdbc:mysql://localhost:3306/court
    username: root
    password: zhouyiran
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  type-aliases-package: com.twinflag.touch.model
  mapper-locations: classpath:mapper/*.xml