spring:
  datasource:
    url: jdbc:mysql://localhost:3306/court
    username: root
    password: zhouyiran
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  freemarker:
    suffix: .html
  http:
    multipart:
      max-file-size: 100Mb
      max-request-size: 1000Mb

