upload-template-path: /Users/zhouyiran/Downloads/uploadTemplate/
upload-material-path: /Users/zhouyiran/Downloads/uploadMatrial/
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/court?useUnicode=true&characterEncoding=utf8
    username: root
    password: zhouyiran
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  freemarker:
    suffix: .ftl
    cache: false
  http:
    multipart:
      max-file-size: 100Mb
      max-request-size: 1000Mb
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${upload-template-path}, file:${upload-material-path}
  mvc:
    static-path-pattern: /**
